name: Format Python
on:
  pull_request:
    paths:
      - "**.py"
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - run: poetry run black . --check
      - name: Install Isort
        run: pip install isort
      - run: poetry run isort . --check-only
